#cloud-config
repo_update: true
repo_upgrade: all
package_update: true
package_upgrade: true
packages:
  - git
  - make
  - docker
  - python3.11
  - python3.11-pip

runcmd:
  - [ ln, -fs, /usr/bin/python3.11, /usr/bin/python3 ]
  - [ systemctl, enable, --now, docker ]
  - [ sh, -c, "usermod -a -G docker ec2-user" ]
  - [ wget, "https://github.com/mikefarah/yq/releases/download/v4.2.0/yq_linux_amd64", -O, /usr/local/bin/yq ]
  - [ chmod, +x, /usr/local/bin/yq ]
  - [ wget, "https://s3.us-west-2.amazonaws.com/amazon-eks/1.29.3/2024-04-19/bin/linux/amd64/kubectl", -O, /usr/local/bin/kubectl ]
  - [ chmod, +x, /usr/local/bin/kubectl ]
  - [ wget, "https://kind.sigs.k8s.io/dl/v0.23.0/kind-linux-amd64", -O, /usr/local/bin/kind ]
  - [ chmod, +x, /usr/local/bin/kind ]
  - [ wget, "https://get.helm.sh/helm-v3.15.2-linux-amd64.tar.gz", -O, /tmp/helm.tar.gz ]
  - [ tar, -xvzf, /tmp/helm.tar.gz, -C, /usr/local/bin/, --strip-components=1, linux-amd64/helm ]
  - [ chmod, +x, /usr/local/bin/helm ]
  - [ su, ec2-user, -lc, 'git clone https://github.com/btuffreau/k8s-playground.git aetion && make -C aetion push' ]
